// Builds the hosted installer Cloudflare Worker.
//
//  1. Embeds the wizard static assets (index.html, app.js, nav.js) from
//     ../installer/public into src/static-assets.ts (generated).
//  2. Pre-bundles the @staticlayer/runtime worker code (via the deployment-core
//     bundler) into src/runtime-bundle.ts (generated) — no esbuild at runtime.
//  3. Bundles src/worker.ts -> dist/worker.js (ESM, Cloudflare Workers).
//
// Prereq: the @staticlayer/protocol package must be built first (its dist/ is
// gitignored): run `npm run build` at the repo root once.

import { build } from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..', '..');

// 1. static assets
function embed(name, path) {
  const content = readFileSync(path, 'utf8');
  return `export const ${name} = ${JSON.stringify(content)};\n`;
}
let staticTs = '// AUTO-GENERATED by build.mjs — do not edit.\n';
staticTs += embed('INDEX_HTML', join(HERE, '..', 'installer', 'public', 'index.html'));
staticTs += embed('APP_JS', join(HERE, '..', 'installer', 'public', 'app.js'));
staticTs += embed('NAV_JS', join(HERE, '..', 'installer', 'public', 'nav.js'));
writeFileSync(join(HERE, 'src', 'static-assets.ts'), staticTs);

// 2. pre-bundle the runtime worker code (same settings as
//    deployment-core/build-worker; inlined so this file runs on Node 20 too —
//    Node 20 cannot import .ts modules directly).
const runtimeResult = await build({
  entryPoints: [join(ROOT, 'packages', 'runtime', 'src', 'index.ts')],
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: 'es2022',
  write: false,
  logLevel: 'silent',
});
const runtimeText = runtimeResult.outputFiles?.[0]?.text;
if (!runtimeText) throw new Error('esbuild produced no output for the runtime worker bundle');
writeFileSync(
  join(HERE, 'src', 'runtime-bundle.ts'),
  `// AUTO-GENERATED by build.mjs — pre-bundled @staticlayer/runtime worker code.\nexport const RUNTIME_WORKER_CODE = ${JSON.stringify(runtimeText)};\n`,
);

// 3. bundle the installer worker
mkdirSync(join(HERE, 'dist'), { recursive: true });
await build({
  entryPoints: [join(HERE, 'src', 'worker.ts')],
  bundle: true,
  format: 'esm',
  platform: 'browser',
  target: 'es2022',
  outfile: join(HERE, 'dist', 'worker.js'),
  logLevel: 'info',
});
console.log('installer-worker: dist/worker.js ready');
