/**
 * FIXED BINARY TEST VECTORS — schema v1.
 *
 * These values were generated by an INDEPENDENT Python implementation
 * (`scripts/gen-vectors.py`, stdlib only: struct/hashlib/hmac/base64) derived
 * directly from the protocol spec — NOT from this TypeScript code.
 *
 * Purpose: if the Worker implementation, the client Web Worker, or any future
 * reimplementation ever produces a different byte sequence / digest for the
 * same logical payload, these tests fail. This is the enforcement point for
 * "the same logical payload => exactly the same byte sequence in every
 * implementation".
 *
 * All integers are BIG-ENDIAN. `challenge_id` and `signature` are serialized
 * in the API as base64url WITHOUT padding.
 */

export const VECTORS = {
  version: 1,
  powSecret: 'staticlayer-test-pow-secret',

  /** Vector A — nominal payload. */
  A: {
    hostContext: 'example.com',
    articlePath: '/blog/hello-world',
    nickname: 'Alice',
    body: 'Hello, world! This is a test comment.',
    // 32 raw bytes: 0x00 0x01 ... 0x1f
    challengeIdHex: '000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f',
    challengeIdBase64Url: 'AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8',
    nonce: '72623859790382856', // 0x0102030405060708
    payloadLen: 121,
    canonicalPayloadHex:
      '01000b6578616d706c652e636f6d00112f626c6f672f68656c6c6f2d776f726c64' +
      '0005416c6963650000002548656c6c6f2c20776f726c6421205468697320697320612074657374' +
      '20636f6d6d656e742e000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d' +
      '1e1f0102030405060708',
    payloadSha256Hex: 'da7b7c64bc22e3d6bc70c46cb39702f25b01a920406c926d3591832a3ababa37',
    expiresAt: '1710000000',
    difficulty: 16,
    canonicalChallengeHex:
      '01000b6578616d706c652e636f6d00112f626c6f672f68656c6c6f2d776f726c64' +
      '000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f0000000065ec87' +
      '8010',
    challengeSignatureHex: '0a4dc5693ecb04388619cda211f26d11302550ea5676b275d29b9bb3847be241',
    challengeSignatureBase64Url: 'Ck3FaT7LBDiGGc2iEfJtETAlUOpWdrJ10pubs4R74kE',
  },

  /** Vector B — boundary lengths (host=255, path=255, nickname=50, body=3000 bytes). */
  B: {
    hostContext: 'h'.repeat(255),
    articlePath: '/'.repeat(255),
    nickname: 'a'.repeat(50),
    body: 'b'.repeat(3000),
    nonce: '0',
    payloadLen: 3611,
    payloadSha256Hex: '990aff443c37a2500a072b3a328b81485984f2f91a2719a46097a9f92e0288cd',
  },

  /** Vector C — valid PoW proof for the nominal fields (difficulty 16). */
  C: {
    hostContext: 'example.com',
    articlePath: '/blog/hello-world',
    nickname: 'Alice',
    body: 'Hello, world! This is a test comment.',
    challengeIdHex: '000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f',
    nonce: '91134',
    sha256Hex: '00007badf6464074ecde066971648000c33ca48af8a5ff915862b85e7a72fe2a',
    leadingZeroBits: 17, // >= 16, so difficulty 16 passes; difficulty 18+ fails
  },
} as const;
