#!/usr/bin/env node
/**
 * Inline the static assets into the runtime as a generated TS module so the
 * Worker can serve them with ZERO runtime dependencies and no special bundler
 * loaders (works identically with Wrangler, esbuild test bundles and tsc).
 *
 * Inputs:  packages/widget/dist/widget.js, pow-worker.js
 *          packages/runtime/static/admin.html, admin.js
 * Output:  packages/runtime/src/static-content.ts  (AUTO-GENERATED)
 *
 * Usage:   npm run build   (after building @staticlayer/protocol + @staticlayer/widget)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

function read(rel) {
  return readFileSync(new URL(rel, import.meta.url), 'utf8');
}

const WIDGET_JS = read('../packages/widget/dist/widget.js');
const POW_WORKER_JS = read('../packages/widget/dist/pow-worker.js');
const ADMIN_HTML = read('../packages/runtime/static/admin.html');
const ADMIN_JS = read('../packages/runtime/static/admin.js');

const out =
  '// AUTO-GENERATED by scripts/sync-static.mjs — DO NOT EDIT BY HAND.\n' +
  '// Regenerate with: npm run build\n\n' +
  `export const WIDGET_JS: string = ${JSON.stringify(WIDGET_JS)};\n\n` +
  `export const POW_WORKER_JS: string = ${JSON.stringify(POW_WORKER_JS)};\n\n` +
  `export const ADMIN_HTML: string = ${JSON.stringify(ADMIN_HTML)};\n\n` +
  `export const ADMIN_JS: string = ${JSON.stringify(ADMIN_JS)};\n`;

const target = new URL('../packages/runtime/src/static-content.ts', import.meta.url);
writeFileSync(target, out, 'utf8');
console.log(
  `static-content.ts generated (widget=${WIDGET_JS.length}B, worker=${POW_WORKER_JS.length}B, admin.html=${ADMIN_HTML.length}B, admin.js=${ADMIN_JS.length}B)`,
);
